-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 12:59:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Voters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voters` (
  `Verified status` TINYINT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `VoterID` INT NOT NULL,
  PRIMARY KEY (`VoterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nominees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nominees` (
  `Names` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `NomineeID` INT NOT NULL,
  PRIMARY KEY (`NomineeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Votes` (
  `VoteID` INT NOT NULL,
  `VoterID` INT NOT NULL,
  `NomineeID` VARCHAR(45) NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`VoteID`, `VoterID`),
  INDEX `fk_Votes_Nominees1_idx` (`NomineeID` ASC) VISIBLE,
  INDEX `fk_Votes_Voters1_idx` (`VoterID` ASC) VISIBLE,
  CONSTRAINT `fk_Votes_Nominees1`
    FOREIGN KEY (`NomineeID`)
    REFERENCES `mydb`.`Nominees` (`NomineeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votes_Voters1`
    FOREIGN KEY (`VoterID`)
    REFERENCES `mydb`.`Voters` (`VoterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ElectionCreator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ElectionCreator` (
  `Email` INT NOT NULL,
  `Username` VARCHAR(100) NOT NULL,
  `Organisation` VARCHAR(45) NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `CreatorID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email`, `CreatorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ElectionCreationEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ElectionCreationEvent` (
  `ElectionCreationID` INT NOT NULL,
  `CreationTime` DATETIME NOT NULL,
  `ElectionID` INT NOT NULL,
  `CreatorID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ElectionCreationID`, `ElectionID`, `CreatorID`),
  INDEX `fk_ElectionCreationEvent_ElectionCreator1_idx` (`CreatorID` ASC) VISIBLE,
  CONSTRAINT `fk_ElectionCreationEvent_ElectionCreator1`
    FOREIGN KEY (`CreatorID`)
    REFERENCES `mydb`.`ElectionCreator` (`CreatorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Election`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Election` (
  `ElectionID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `ElectionCode` INT NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NOT NULL,
  PRIMARY KEY (`ElectionID`, `ElectionCode`),
  CONSTRAINT `fk_Election_ElectionCreationEvent1`
    FOREIGN KEY (`ElectionID`)
    REFERENCES `mydb`.`ElectionCreationEvent` (`ElectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VotingEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VotingEvent` (
  `VotingEventID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `EligibilityStatus` VARCHAR(45) NOT NULL,
  `ElectionID` INT NOT NULL,
  `VoterID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VotingEventID`, `VoterID`, `ElectionID`),
  INDEX `fk_VotingEvent_Election1_idx` (`ElectionID` ASC) VISIBLE,
  INDEX `fk_VotingEvent_Voters1_idx` (`VoterID` ASC) VISIBLE,
  CONSTRAINT `fk_VotingEvent_Election1`
    FOREIGN KEY (`ElectionID`)
    REFERENCES `mydb`.`Election` (`ElectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VotingEvent_Voters1`
    FOREIGN KEY (`VoterID`)
    REFERENCES `mydb`.`Voters` (`VoterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParticipationEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParticipationEvent` (
  `ParticipationID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `ElectionID` INT NOT NULL,
  `NomineeID` INT NOT NULL,
  PRIMARY KEY (`ParticipationID`, `ElectionID`, `NomineeID`),
  INDEX `fk_ParticipationEvent_Election1_idx` (`ElectionID` ASC) VISIBLE,
  INDEX `fk_ParticipationEvent_Nominees1_idx` (`NomineeID` ASC) VISIBLE,
  CONSTRAINT `fk_ParticipationEvent_Election1`
    FOREIGN KEY (`ElectionID`)
    REFERENCES `mydb`.`Election` (`ElectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ParticipationEvent_Nominees1`
    FOREIGN KEY (`NomineeID`)
    REFERENCES `mydb`.`Nominees` (`NomineeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmailVerificationEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmailVerificationEvent` (
  `VerificationID` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `VerificationCode` INT NOT NULL,
  `ExpirationTime` TIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VerificationID`, `Email`),
  INDEX `fk_EmailVerificationEvent_Voters1_idx` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_EmailVerificationEvent_Voters1`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Voters` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
