-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 15:07:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Nominee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nominee` (
  `NomineeID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `PositionID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Score` VARCHAR(45) NOT NULL,
  `ElectionID` INT NOT NULL,
  PRIMARY KEY (`NomineeID`, `PositionID`, `ElectionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Election`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Election` (
  `ElectionID` INT NOT NULL,
  `ElectionName` VARCHAR(45) NOT NULL,
  `Desciption` VARCHAR(45) NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NOT NULL,
  `ShowResults` TINYINT NOT NULL,
  CONSTRAINT `fk_Election_Nominee1`
    FOREIGN KEY (`ElectionID`)
    REFERENCES `mydb`.`Nominee` (`ElectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Position` (
  `PositionID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `ElectionID` INT NOT NULL,
  PRIMARY KEY (`PositionID`, `ElectionID`),
  CONSTRAINT `fk_Position_Nominee1`
    FOREIGN KEY (`PositionID`)
    REFERENCES `mydb`.`Nominee` (`PositionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voter` (
  `VoterID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `VerifiedStatus` TINYINT NOT NULL,
  `ElectionID` INT NOT NULL,
  PRIMARY KEY (`VoterID`),
  INDEX `fk_Voter_Election1_idx` (`ElectionID` ASC) VISIBLE,
  CONSTRAINT `fk_Voter_Election1`
    FOREIGN KEY (`ElectionID`)
    REFERENCES `mydb`.`Election` (`ElectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
